### PR TITLE
fix(p-search-dropdown): fix dropbox overlap issue

### LINKED ISSUE #21: Dropboxes overlap
Image

### PR DESCRIPTION
**Pull request by piggggggggy**
### To Reviewers
- [ ] Skipping review is not a problem (```style```, ```chore``` ONLY)
- [ ] Not that difficult

### Type of Change
- [ ] New feature
- [x] Bug fixes
- [ ] Feature improvement
  - [ ] These changes require a usage change
- [x] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [ ] Updated Storybook documents
- [x] Tested with console

### Description
- fix `Dropboxes overlap #21` 
- add `@vueuse/components`, `@vueuse/core` package
- add `vOnClickOutside` and remove eventListener in `p-search-dropdown`
- add additional config-module-rule in storybook

### CODE REVIEW

File: .storybook/main.js [hunk 1]
```diff
@@ -58,8 +58,18 @@ module.exports = {
...
     });
 
+    /* for 'Can't import the named export from non EcmaScript module' issue while using '@vueuse/components' */
+    /* https://github.com/vuejs/pinia/issues/675 */
+    config.module.rules.push({
+      test: /\.mjs$/,
+      include: /node_modules/,
+      type: 'javascript/auto',
+    });
+
```
Comment (yuda110) [inline .storybook/main.js:68]: 😲

**Review by yuda110 — APPROVED** [review]
LGTM!!!
